import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import { AuthProvider } from '@/contexts/AuthContext'
import { CategoryProvider } from '@/contexts/CategoryContext'
import { EventProvider } from '@/contexts/EventContext'
import { BookingProvider } from '@/contexts/BookingContext'
import { CustomerProvider } from '@/contexts/CustomerContext'

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};




export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body>
        <AuthProvider>
            <CategoryProvider>
                <EventProvider>
                    <BookingProvider>
                        <CustomerProvider>
                            {children}
                        </CustomerProvider>
                    </BookingProvider>
                </EventProvider>
            </CategoryProvider>
        </AuthProvider>
        </body>
        </html>
    )
}




